/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React  from 'react';
import { Platform,Button, StyleSheet, Text, View } from 'react-native';
import Plus,{ Portal,Component } from 'react-native-plus';

export default class App extends Component{
  state = {
    status: 'starting',
    message: '--'
  };
  componentDidMount() {
    Plus.sampleMethod('Testing', 123, (message) => {
      this.setState({
        status: 'native callback received',
        message
      });
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Portal/>
        <Button title={"点击显示toast在顶部"} onPress={()=>Plus.showToast('hello toast')}/>
        <Button title={"点击显示toast在中部"} onPress={()=>Plus.showToast({ title:"hello",duration: Plus.Toast.DURATION.LONG,position: Plus.Toast.POSITION.CENTER })}/>
        <Button title={"点击显示toast在底部"} onPress={()=>Plus.showToast({ title:"hello",duration: Plus.Toast.DURATION.LONG,position: Plus.Toast.POSITION.BOTTOM })}/>

        <Button title={"点击显示loading"} onPress={()=>{
          Plus.showLoading('数据加载中...');
          setTimeout(() =>{
            Plus.hideLoading()
          },2000)
        }}/>

        <Button title={"点击显示loading 主题2"} onPress={()=>{
          Plus.showLoading({
            title:'数据加载中...',
            theme: Plus.Loading.THEME.THEME2
          });
          setTimeout(() =>{
            Plus.hideLoading()
          },2000)
        }}/>

        <Button title={"点击显示loading 主题3"} onPress={()=>{
          Plus.Loading.setIndicatorProps({ // 设置loading的颜色
            color:'#f50', size:'large' })
          Plus.showLoading({
            title:'数据加载中...',
            theme: Plus.Loading.THEME.THEME3
          });
          setTimeout(() =>{
            Plus.hideLoading()
          },2000)
        }}/>
        <Button title={"点击显示action sheet"} onPress={()=>{
          Plus.showActionSheet({
            title:'请选择',
            message:'请选择一种水果',
            itemList: ['香蕉','梨子','关闭'],
            success(tapIndex) {
              console.log(tapIndex)
            }
          });
        }}/>

        <Button title={"点击显示弹框"} onPress={()=>{
          Plus.showModal({
            title:"消息",
            message:'hello world',
            onConfirm(){
              Plus.hideModal()
            }
          });
        }}/>

        <Text style={styles.welcome}>☆Plus example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
